services:
  lightnvr:
    build: .
    container_name: lightnvr
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "1984:1984"  # go2rtc API port
    volumes:
      - ./config:/etc/lightnvr
      - ./data:/var/lib/lightnvr/data
    environment:
      - TZ=UTC  # Set timezone, change as needed
